### ISSUE TITLE
oauth2 instagram

### ISSUE THREAD

**Issue by Bellafkb** [Bellafkb/how-to-club-backend#2]

**Comment by Bellafkb** [comment]
bug needs hot fix

**Comment by Bellafkb** [comment]
failed to fetch user profile
InternalOAuthError: failed to fetch user profile
    at /Users/mac/Desktop/how-to-club-backend/node_modules/passport-instagram/lib/strategy.js:80:28
    at passBackControl (/Users/mac/Desktop/how-to-club-backend/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/mac/Desktop/how-to-club-backend/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by Bellafkb** [comment]
was a bug on the instagram side. I ll close this one.
